example: fError
CallStack (from HasCallStack):
  error, called at example/Main.hs:47:10 in main:Main
  fError, called at example/Main.hs:43:11 in main:Main
  f10, called at example/Main.hs:40:6 in main:Main
  f9, called at example/Main.hs:37:11 in main:Main
  f8, called at example/Main.hs:33:16 in main:Main
  f7, called at example/Main.hs:29:11 in main:Main
  f6, called at example/Main.hs:25:15 in main:Main
  f5, called at example/Main.hs:21:8 in main:Main
  f4, called at example/Main.hs:17:6 in main:Main
  f3, called at example/Main.hs:13:6 in main:Main
  f2, called at example/Main.hs:10:6 in main:Main
  f1, called at example/Main.hs:7:14 in main:Main
  main, called at example/Main.hs:7:1 in main:Main
